scss_files: "scss/*.scss"

exclude: "scss/_normalize.scss"

linters:
  PropertySortOrder:
    order: smacss

  SingleLinePerSelector:
    enabled: false

  ImportantRule:
    enabled: false

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true

  SelectorDepth:
    max_depth: 4
